### ISSUE TITLE
Text disappears 

### ISSUE THREAD

**Issue by revad** [GoAlexander/harbour-editor#112]
SFOS 3.0.1.11 Jolla C v0.8.5
The text, unsaved,  disappears. Usually after reopening editor after a long period using other apps. Cover shows lines, chars but editor screen blank.

**Comment by GoAlexander** [comment]
Hi, Is the bug still relevant for version 0.9 of app?

**Comment by revad** [comment]
Sorry, no idea. I haven't used it much since then and SFOS has been updated too.
I'll close this.

**Comment by GoAlexander** [comment]
Ok, any way thanks for the feedback :)
