### ISSUE TITLE
[ Suggestions to Editor ]

### ISSUE THREAD

**Issue by Caballlero** [GoAlexander/harbour-editor#53]
First thanks for: editor. New icon it pretty.
- I would like to know if there is a way that only one line and not two of the same sentence
![captura_20170401_001](https://cloud.githubusercontent.com/assets/24536606/24581795/3e686b8a-16f0-11e7-8cc7-85a95b14c6d8.png)
- I would like it personally that the icon in the multitasking would appear as well as the wunderfitz app. And put that icon you have current in multitasking in about of: editor --- Many sailfish app follow this view as wunderfitz in multitasking : )
![captura_20170401_003](https://cloud.githubusercontent.com/assets/24536606/24581827/df890c54-16f0-11e7-864d-918d8c08e106.png)

- thanks, i just sharing my ideas. have good day.

**Comment by GoAlexander** [comment]
1) Try option "Quick menu enabled" in the settings or you want to disable this line in pull menu?

2) Maybe in the feature. Good idea. Now I want to implement some features for code writting and some backend improvements.

**Comment by GoAlexander** [comment]
All suggestions implemented. Will be in the next version - 0.7

**Comment by Caballlero** [comment]
thanks you.
