### ISSUE TITLE
Editor loads backup file instead of original

### ISSUE THREAD

**Issue by Self-Perfection** [GoAlexander/harbour-editor#68]
Version: harbour-editor-0.7-1

Suppose there are two files with different content:
* `~/Notes/Unsorted/Jolla.txt`
* `~/Notes/Unsorted/Jolla.txt~`

And user launches editor:
`harbour-editor  ~/Notes/Unsorted/Jolla.txt`

The Editor shows contents of file `Jolla.txt~`.

Typical scenario: user opens `foo.txt`, makes edits, saves file (Editor makes a backup), closes Editor. After a while user opens file with Editor again and _gets old content_, it seems that previous edit was lost.

...
...

How is it possible that such was not noticed before release?!?!

**Comment by GoAlexander** [comment]
I checked this scenario on my phone. Yes, bug reproduced. Thank you for the report. I hope that you did not lost your data.  
I develop this app alone so I did not mention it while tested.
  
I will try to publish quick fix soon as possible.

**Comment by GoAlexander** [comment]
a9db35e75dd3426d885b4014c21ba7463228cc29

**Comment by GoAlexander** [comment]
Test version 0.7.1 (soon in all markets). Bug should be fixed

**Comment by Self-Perfection** [comment]
Thank you for your concern for my data. It is intact.

I've just tried version 0.7.1-1 from Jolla store. The issue is **NOT** fixed.

**Comment by GoAlexander** [comment]
I reread your issue I understood description incorrect (but last version really fixes bug with auto-save). I hope that this time I understood it right:  
  
I do not see any strange or incorrect behavior in your description. Please read description of Editor again (in harbour or openrepos):
`- Autosave of your text in special file ending with ~, located in the directory where your original file is located. Do not be afraid to forget to save the file or accidentally exit the app!`
`- Do not open files which ending with ~. The last version of document will be loaded automatically. So load only(!) original files.`

So firstly concerning description above the behavior of app is ok. If file with same name and ~ exists -> it will be opened. +The most actual data is in ~ file all time (I can not imagine the situation when this is inversely).
Second "mistake" in your description: If you saved changes file with ~ does not exist. File with ~ exists ONLY if you make changes and do not press button `Save`.

P.S.
If you want we can discuss this in Russian. I am from Russia too :)

**Comment by Self-Perfection** [comment]
Aha it makes more sense after your clarification. Thus, in other words app saves edited version of file just in case if a user closes the app with edited text buffer and have not explicitly commanded to save file. Still it is not clear for me whether the app flushes text buffer to `$FN~` by timer just in case OS hang or app crash.

This behavior is counter intuitive for me: traditionally ~ files are used for backups, i.e. contain _old_ file version. Indeed description for user is required. Probably help text on the first app run. I suppose description text should be improved. It should describe the app behavior in more details.

I'd like to have an option to autosave directly to *.txt. Though I might have peculiar and uncommon use case. You see, I have a bunch of txt files in synced directory between phone and PC. On PC I use [zim](http://zim-wiki.org/) to manage this notes. zim ignores txt~ files. So I might end up having newer version in txt~ (via Editor), then editing same note via zim (thus editing older version). And afterwards I'll have two files with different modifications that might be arduous to merge. 

----
После вашего пояснения стало понятнее.  Итак, если пользователь отредактировал файл, но не нажимал явным образом "сохранить", то отредактированная версия будет сохранена в файле txt~, а оригинальный файл не будет модифицирован. Мне однако не ясно, происходит ли автоматическое сохранение по таймеру, на случай краша приложения или зависания ОС.

Текущее поведение приложения контринтутивно для меня. Традиционно в txt~ файле хранится более старая версия файла. Я думаю можно улучшить справку, подробнее описав поведение приложения, и стоит её показывать при первом запуске программы.

Мне хотелось бы иметь опцию, которая бы выключала использование txt~ файлов для автосохранения, а автосохраняла бы в txt. Хотя, возможно, у меня специфическая ситуация. У меня есть синхронизируемая между мобилой и десктопом директория с txt заметками. На десктопе я использую [zim](http://zim-wiki.org/) для управления этими заметками, zim просто не видит txt~ файлы, так что я могу поправить на ПК txt файл с более старым содержимым по сравнению с txt~, и тогда txt версия станет _новее_.

**Comment by GoAlexander** [comment]
Which language do you prefer? :)
Отвечу на русском для быстроты.
  

> После вашего пояснения стало понятнее. Итак, если пользователь отредактировал файл, но не нажимал явным образом "сохранить", то отредактированная версия будет сохранена в файле txt~, а оригинальный файл не будет модифицирован.


 Да, Вы правильно поняли логику работы. 

> Мне однако не ясно, происходит ли автоматическое сохранение по таймеру, на случай краша приложения или зависания ОС.

Лучше! Сохранение происходит во время изменения текста, у компонента `TextArea` есть свойство `onTextChanged`, вот я его и использую.

> Текущее поведение приложения контринтутивно для меня. Традиционно в txt~ файле хранится более старая версия файла. Я думаю можно улучшить справку, подробнее описав поведение приложения, и стоит её показывать при первом запуске программы.

Это авторская фишка, вряд ли буду так кардинально менять логику. Насчет справки согласен, если кто-то ее напишет, к примеру Вы, то с радостью интегрирую в приложение, как время будет. :)

> Мне хотелось бы иметь опцию, которая бы выключала использование txt~ файлов для автосохранения, а автосохраняла бы в txt. Хотя, возможно, у меня специфическая ситуация. У меня есть синхронизируемая между мобилой и десктопом директория с txt заметками. На десктопе я использую zim для управления этими заметками, zim просто не видит txt~ файлы, так что я могу поправить на ПК txt файл с более старым содержимым по сравнению с txt~, и тогда txt версия станет новее.

Насчет этой опции для смены автосохранения согласен, реализовать можно, заведите, пожалуйста, issue.  
Я тоже использую zim на десктопе, даже были планы по интеграции в To Do листе, но были более приоритетные задачи. Так что если есть какие-то идеи - welcome :)


> так что я могу поправить на ПК txt файл с более старым содержимым по сравнению с txt~, и тогда txt версия станет новее.

Прошу заметить, что как только вы нажали на кнопку `Save`, то файл с ~ автоматически удалится.

P.S. 
Если у Вас есть еще вопросы по различным темам, то предлагаю перейти в телеграм: @GoAlexander

**Comment by GoAlexander** [comment]
Также если есть желание/энергия, то предлагаю Вам контрибьютить в проект. Я всегда рад сотрудничеству. :)
Потенциальный фронт работы большой: https://trello.com/b/Gyu7pPqi/harbour-editor
Языки используются разные (QML, JS, C++, Python).

**Comment by Self-Perfection** [comment]
> Which language do you prefer? :)

I'm equally comfortable with discussion IT topics in Russian and English, but it seems to me English should prefered on github to let anyone participate in a project. But I give up, let's use Russian here for consistency. There is Google Translate for those who do not speak Russian.

> Лучше! Сохранение происходит во время изменения текста, у компонента `TextArea` есть свойство `onTextChanged`, вот я его и использую.

То есть Editor. записывает на флэшку файл после каждого напечатанного символа? Но это же очень неэффективно! Вот что например будет, если директория с файлом расположена на файловой системе, примонтированной через сеть с высокой латентностью, эдак под секунду? Оптимальный вариант: на onTextChanged запускать таймер на 5 секунд, если нет работающего таймера, и по истечению интервала сбрасывать текстовый буфер в файл автосохранения + автосохранять при выходе.

> So firstly concerning description above the behavior of app is ok. If file with same name and ~ exists -> it will be opened. +The most actual data is in ~ file all time (I can not imagine the situation when this is inversely).

Вообще по размышлению таких ситуаций может быть множество. Например я долгое время пользовался vim настроенным сохранять бэкап файл с именем $FN~ - в бэкапе более старая версия файла. А ещё я сейчас потестировал редактирование текстового файла на смонтированной через sshfs по 2G файловой системе. Автосохранение смогло создать файл `tesfile.txt~`, но он почему-то был пустым. Возможно `open()` обработался, а на `write()` сотовая связь отвалилась. И я пару минут протыкался не в силах понять, почему при последующих запусках Editor. не читает `testfile.txt` по сети, пока не понял, что читается пустой `testfile.txt~`. И это притом, что я уже в курсе про механизм работы автосохранения, что подтверждает его некоторую контринтуитивность.

Я убеждён, что  механизм автосохранения должен быть изменён, чтобы подобных проблем не возникало. Предложения:
* Стоит сравнивать modification time оригинального файла и файла автосохранения, и читать последний при загрузке только если он новее. 
* Возможно стоит изменить постфикс для файла автосохранения. Например вместо ~ использовать `.editor.autosave`
* Стоит иметь ввиду для надёжности, что open->write сильно не атомарен, а mv атомарен. Т.е. надёжный алгоритм автосохранения: создать файл `$FN.editor.autosave~`, записать в него текстовый буфер, **в случае успеха** переименовать в `$FN.editor.autosave` (заменив тем самым предыдущий бэкап).
