### ISSUE TITLE
Editor. switches font after loading

### ISSUE THREAD

**Issue by Self-Perfection** [GoAlexander/harbour-editor#73]
If Editor is launched to open specific file with command line parameter: `harbour-editor /home/nemo/test.txt` it shows this text with one font for a fraction of a second, then font changes. Or maybe it is only size of the font.

This is a bit annoying and I suppose increases loading time a bit.

Другими словами: при запуске с параметром командной строки пути к документу, документ сначала рендерится, потом загружаются настройки шрифта, потом документ рендерится снова. Может стоит опустить первый рендер, до загрузки параметров шрифта?

**Comment by GoAlexander** [comment]
I can`t reproduce bug or it loads too fast on my phone (so I can` t see it). How big is your `test.txt`?

**Comment by Self-Perfection** [comment]
I've performed more tests on my side and here are my findings.

The bug is reproducible not always, but like 30% of app launches. I'm not sure if file size matters. I've reproduced with files about 2KiB.

I've tried to catch screenshot with improper font at the start. This cmd
```bash
harbour-editor  ~/README.txt & sleep 3; grabscreen /home/nemo/$(date +%H%M%S).png
```
worked after several attemps, though it catches screenshot during transition animation.

Here is the screenshot from proper loading:
![192843](https://cloud.githubusercontent.com/assets/3757038/26414827/065c9c32-40b9-11e7-8953-497c1033739f.png)

and here is the screenshot with wrong font
![192856](https://cloud.githubusercontent.com/assets/3757038/26414840/0da00650-40b9-11e7-9e42-25c1c9211d1d.png)
after a fraction of second text area was rerendered with proper arial.

BTW, my device is Jolla C with SailfishOS 2.1.0.11 (Iijoki)

Note that on screenshot with wrong font toolbar is not visible. Does it give a clue?

**Comment by GoAlexander** [comment]
Hm... It seems that this bug is on the side of QML core/QT... 
First of all I have to reproduce this bug (I will use your script) then I will see if it is possible to fix it.
I see this behaviour first time...

**Comment by Self-Perfection** [comment]
I'd like to clarify. If Editor loads initially with wrong font it seems it always misses toolbar at this stage, but when editor finally redraws itself with proper font the toolbar is present. I have not even noticed that toolbar is missing in such cases until I made several screenshots.

**Comment by GoAlexander** [comment]
Yeah I understood.

**Comment by Self-Perfection** [comment]
It seems upgrading to 0.8.2 resolved the issue. Also the app seems to start faster after upgrade.

**Comment by GoAlexander** [comment]
Wow, I like to hear it :)
Thanks for the feedback.
