### ISSUE TITLE
feature request:  better support to .XML format

### ISSUE THREAD

**Issue by Caballlero** [GoAlexander/harbour-editor#77]
----------

**Comment by GoAlexander** [comment]
Please explain more what you want exactly? You mean syntax highlighting?

**Comment by Caballlero** [comment]
when i editing files in format .xml using editor. like feeling freeze, not feeling smooth .

**Comment by GoAlexander** [comment]
How big is your .xml file?
It is ok if you have some freezes in the big files >1000. I have rewrite some code to improve the performance :)

**Comment by Caballlero** [comment]
look fixed by current release :  )
