### ISSUE TITLE
[Usability issue] Eliminate large empty vertical spaces in Editor.'s pulley menu

### ISSUE THREAD

**Issue by Olf0** [GoAlexander/harbour-editor#81]
Please eliminate the large empty vertical spaces in Editor.'s top pulley menu: 
- Eliminate the large space above "Settings". 
- Shrink the vertical margins around the file path, if possible (its font size is good and should stay, IMO).  You might even eliminate the large empty space below the pulley menu's  second icon row (i.e. above the regular top screen icon row) completely, when no file path is currently set, but that may not be worth the effort. 
- The vertical space between the two icon rows in the pulley menu seems to be a bit larger than the vertical space between the word "Settings" and the first icon row there: If I am right, please shrink the former vertical space to the size of the latter. 
- [Further suggestion] The icons in the regular (top screen) icon row below are (rightly) all "grayed out", when the pulley menu is pulled.  Hence it would be a better use of the available screen space not to display them at all in this situation. 

- [Even further reaching suggestion] Separate out the "Settings" pulley entry to a bottom pulley. 

This usability issue is much more prominent in landscape orientation:

![screenshot_jolla1-landscape](https://cloud.githubusercontent.com/assets/16547876/26745248/fcfe6bb0-47e9-11e7-95cf-f64abacee7be.png)

![screenshot_jolla1-portrait](https://cloud.githubusercontent.com/assets/16547876/26745305/2ea61d52-47ea-11e7-8cd5-28de16cf4e58.png)

**Comment by GoAlexander** [comment]
First of all I want to say that "UI 2.0" is in hard development. I will change some logic.
By this time I replaced position of toolbar and menu:
![photo_2017-05-27_15-52-03](https://cloud.githubusercontent.com/assets/13280035/26753423/795c0f3a-486e-11e7-855b-5f3cae05ac27.jpg)

The next step is changing of pulley menu - it will be (I think) without the buttons it will contain only MenuItems (as Settings option) but the will be special external page where will be all NOT  often using buttons.
This changing is on the basis of all user`s feedback and my personal experience :)

**Comment by GoAlexander** [comment]
> Eliminate the large space above "Settings".

I can`t change it because it is default behavior of the system.
(I saw something like you said in apps of CodeRus but it is something like hacking I think :) )

> Shrink the vertical margins around the file path, if possible (its font size is good and should stay, IMO). You might even eliminate the large empty space below the pulley menu's second icon row (i.e. above the regular top screen icon row) completely, when no file path is currently set, but that may not be worth the effort.

I know this bug and I don`t know how to fix it :(

> The vertical space between the two icon rows in the pulley menu seems to be a bit larger than the vertical space between the word "Settings" and the first icon row there: If I am right, please shrink the former vertical space to the size of the latter.

In case of UI 2.0 I think it will be no longer relevant.

> [Further suggestion] The icons in the regular (top screen) icon row below are (rightly) all "grayed out", when the pulley menu is pulled. Hence it would be a better use of the available screen space not to display them at all in this situation.

Good suggestion. I will mention it in my ToDo but will implement it only in far future ) (there is another priorities)

> [Even further reaching suggestion] Separate out the "Settings" pulley entry to a bottom pulley.

Also not longer relevant in case of UI 2.0 but I will explain one think that I see not all users of Editor understand:
**I implemented toolbar also for the case when you are in the center of large document and do not want to scroll at the top to open menu. With toolbar you can press it and swype and menu wiil be opened in the center of the document!**

**Comment by Olf0** [comment]
Hello @GoAlexander, 
a. The screenshot of Editor.'s UI 2.0 with the moved toolbar (to the top of the vKeyboard) looks like a good / improved layout. 
b. Unfixable bugs: Well, that's life. ;)
c. As you noted the only left over item (not covered by a. or b.: to "gray out" the toolbar, when it is inaccessible, anyway), closing this issue.

**Comment by Olf0** [comment]
Well, the situation is definitely enhanced with the "UI 2.0", which first appeared in Editor. v0.8: 
There is only a single vertical space remaining, which is now *below* the pulley entry "Settings". 
See 
![screenshot_editor -0 8_bottom-pulley](https://user-images.githubusercontent.com/16547876/28039162-8ff3b12e-65c1-11e7-9752-d3e431adb025.png)
and
![screenshot_editor -0 8_bottom-pulley-above-vkeyboard](https://user-images.githubusercontent.com/16547876/28039195-aac68fa8-65c1-11e7-8978-e8bc20a8d4e4.png)
Tested with Editor. v0.8 on a Jolla 1 phone under SailfishOS 2.1.0.11

**Comment by GoAlexander** [comment]
Do you like it? I reduced the space.

**Comment by Olf0** [comment]
The vertical spaces above and below that pulley menu entry "Settings" are fine with Editor. 0.84.  
And it makes a difference, especially in landscape orientation:

![screenshot_20180425_002](https://user-images.githubusercontent.com/16547876/39220460-850919ae-4831-11e8-807d-958c7b17083a.png)

Side note: I wonder, why the vertical space above the file path looks quite large [in your screenshot](https://www.dropbox.com/s/6lhsqerzieex1mg/Screenshot_20180424_001.png), but not on my Jolla 1 with Editor. 0.84 (regardless if using it in landscape or portrait orientation).

**Comment by Olf0** [comment]
BTW & OT: Editor. 0.8.3 was not available in the Jolla Store (currently v0.8.2 is the latest version there, AFAICS), hopefully v0.8.4 will make it.

**Comment by GoAlexander** [comment]
0.8.3 was to able because of a bug in history. 0.8.4 is in Jolla moderation.

**Comment by GoAlexander** [comment]
I see that I fixed huge part of your requests here ao I will close this issue.
